wget https://www.onvif.org/ver10/accessrules/wsdl/accessrules.wsdl -P ./src/main/resources/onvif/ver10/accessrules/wsdl/
wget https://www.onvif.org/ver10/actionengine.wsdl -P ./src/main/resources/onvif/ver10/
wget https://www.onvif.org/ver10/advancedsecurity/wsdl/advancedsecurity.wsdl -P ./src/main/resources/onvif/ver10/advancedsecurity/wsdl/
wget https://www.onvif.org/ver10/appmgmt/wsdl/appmgmt.wsdl -P ./src/main/resources/onvif/ver10/appmgmt/wsdl/
wget https://www.onvif.org/ver10/authenticationbehavior/wsdl/authenticationbehavior.wsdl -P ./src/main/resources/onvif/ver10/authenticationbehavior/wsdl/
wget https://www.onvif.org/ver10/credential/wsdl/credential.wsdl -P ./src/main/resources/onvif/ver10/credential/wsdl/
wget https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl -P ./src/main/resources/onvif/ver10/device/wsdl/
wget https://www.onvif.org/ver10/deviceio.wsdl -P ./src/main/resources/onvif/ver10/
wget https://www.onvif.org/ver10/display.wsdl -P ./src/main/resources/onvif/ver10/
wget https://www.onvif.org/ver10/events/wsdl/event.wsdl -P ./src/main/resources/onvif/ver10/events/wsdl/
wget https://www.onvif.org/ver10/media/wsdl/media.wsdl -P ./src/main/resources/onvif/ver10/media/wsdl/
wget https://www.onvif.org/ver10/pacs/accesscontrol.wsdl -P ./src/main/resources/onvif/ver10/pacs/
wget https://www.onvif.org/ver10/pacs/doorcontrol.wsdl -P ./src/main/resources/onvif/ver10/pacs/
wget https://www.onvif.org/ver10/provisioning/wsdl/provisioning.wsdl -P ./src/main/resources/onvif/ver10/provisioning/wsdl/
wget https://www.onvif.org/ver10/receiver.wsdl -P ./src/main/resources/onvif/ver10/
wget https://www.onvif.org/ver10/recording.wsdl -P ./src/main/resources/onvif/ver10/
wget https://www.onvif.org/ver10/replay.wsdl -P ./src/main/resources/onvif/ver10/
wget https://www.onvif.org/ver10/schedule/wsdl/schedule.wsdl -P ./src/main/resources/onvif/ver10/schedule/wsdl/
wget https://www.onvif.org/ver10/search.wsdl -P ./src/main/resources/onvif/ver10/
wget https://www.onvif.org/ver10/thermal/wsdl/thermal.wsdl -P ./src/main/resources/onvif/ver10/thermal/wsdl/
wget https://www.onvif.org/ver10/uplink/wsdl/uplink.wsdl -P ./src/main/resources/onvif/ver10/uplink/wsdl/
wget https://www.onvif.org/ver20/analytics/wsdl/analytics.wsdl -P ./src/main/resources/onvif/ver20/analytics/wsdl/
wget https://www.onvif.org/ver20/imaging/wsdl/imaging.wsdl -P ./src/main/resources/onvif/ver20/imaging/wsdl/
wget https://www.onvif.org/ver20/media/wsdl/media.wsdl -P ./src/main/resources/onvif/ver20/media/wsdl/
wget https://www.onvif.org/ver20/ptz/wsdl/ptz.wsdl -P ./src/main/resources/onvif/ver20/ptz/wsdl/
wget https://www.onvif.org/ver10/schema/onvif.xsd -P ./src/main/resources/onvif/ver10/schema/
wget https://www.onvif.org/ver10/schema/common.xsd -P ./src/main/resources/onvif/ver10/schema/
wget https://www.onvif.org/ver10/schema/metadatastream.xsd -P ./src/main/resources/onvif/ver10/schema/
wget https://www.onvif.org/ver10/pacs/types.xsd -P ./src/main/resources/onvif/ver10/pacs/
wget https://www.onvif.org/ver20/analytics/rules.xsd -P ./src/main/resources/onvif/ver20/analytics/
wget https://www.onvif.org/ver20/analytics/humanbody.xsd -P ./src/main/resources/onvif/ver20/analytics/
wget https://www.onvif.org/ver20/analytics/humanface.xsd -P ./src/main/resources/onvif/ver20/analytics/
